name: flutter_event_manager
description: A flutter project that helps introduce event based development to dart. Note that there are no tests to this project as the class is straight forward and simple
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
